# Generated by Django 4.1.2 on 2022-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved_albums',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
