# Generated by Django 4.1.3 on 2022-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_creation_datetime_album_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateField(),
        ),
    ]
