# Generated by Django 4.1.3 on 2022-11-14 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_release_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('song_img', models.ImageField(upload_to='data/images')),
                ('thumbnail', models.ImageField(upload_to='data/thumbs')),
                ('song_file', models.FileField(upload_to='data/media', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
