# Generated by Django 4.1.3 on 2022-11-16 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_song_name_alter_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='static/albums/data/media', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.ImageField(upload_to='static/albums/data/images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(upload_to='static/albums/data/thumbs'),
        ),
    ]
